shared:
  image: node:6

jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - hello: echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
               echo "hello world"
      - exit: exit 1
      - do_not_run: echo "will not run"
      - teardown-lusol: echo bye
